local_vars:
  watersharing:
    ex_path: "./export_local/watersharing"
    in_path: "./import_local/watersharing"
  watertrading:
    ex_path: "./export_local/watertrading"
    in_path: "./import_local/watertrading"

production_vars:
  watersharing:
    ex_path: "/var/www/share.producedwater.org/wp-content/plugins/watersharing-wp/io/watersharing/export/"
    in_path: "/var/www/share.producedwater.org/wp-content/plugins/watersharing-wp/io/watersharing/import/"
  watertrading:
    ex_path: "/var/www/share.producedwater.org/wp-content/plugins/watersharing-wp/io/watertrading/export/"
    in_path: "/var/www/share.producedwater.org/wp-content/plugins/watersharing-wp/io/watertrading/import/"
